http {
    proxy_connect_timeout 3600; # Timeout for establishing a connection with a proxied server.
    proxy_send_timeout 3600; # Timeout for sending a request to the proxied server.
    proxy_read_timeout 3600; # Timeout for reading a response from the proxied server.

    # # Round Robin
    # upstream backends {
    #     server server-1;
    #     server server-2;
    #     server server-3;
    # }

    # # Least Connections or IP Hash
    # upstream backends {
    #     least_conn;
    #     # ip_hash;
    #     server server-1;
    #     server server-2;
    #     server server-3;
    # }

    # Round Robin with weight
    upstream backends {
        server server-1 weight=5;
        server server-2;
        server server-3;
    }

    server {
        listen 9999; # Port to listen on
        location / {
            proxy_pass http://backends/;
        }
    }
}

events {
    worker_connections 512;
}
