services:
  namenode:
    build: ./namenode
    container_name: namenode
    volumes:
      - ../hadoop_demo:/hadoop_demo
    environment:
      - CLUSTER_NAME=demoo
    ports:
      - "9870:9870"

  datanode1:
    build: ./datanode
    container_name: datanode1
    depends_on:
      - namenode

  datanode2:
    build: ./datanode
    container_name: datanode2
    depends_on:
      - namenode

  datanode3:
    build: ./datanode
    container_name: datanode3
    depends_on:
      - namenode

  datanode4:
    build: ./datanode
    container_name: datanode4
    depends_on:
      - namenode

  resourcemanager:
    build: ./resourcemanager
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - datanode4
    ports:
      - "8088:8088"

  nodemanager1:
    build: ./nodemanager
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - datanode4
    ports:
      - "8042:8042"

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "9090:8080"
    volumes:
      - ../hadoop_demo:/hadoop_demo
      - ../spark_demo:/spark_demo
      - ../kafka_demo:/kafka_demo
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - datanode4
      - nodemanager1
    environment:
      - SPARK_HOME=/spark
      - PATH=${PATH}:/spark/bin
      - HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop

  spark-worker:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker
    depends_on:
      - spark-master

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - ../hadoop_demo:/hadoop_demo
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - zookeeper
