services:
  namenode:
    build: ./namenode
    container_name: namenode
    environment:
      - CLUSTER_NAME=demoo
    ports:
      - "9870:9870"

  datanode1:
    build: ./datanode
    container_name: datanode1
    depends_on:
      - namenode

  datanode2:
    build: ./datanode
    container_name: datanode2
    depends_on:
      - namenode

  datanode3:
    build: ./datanode
    container_name: datanode3
    depends_on:
      - namenode

  datanode4:
    build: ./datanode
    container_name: datanode4
    depends_on:
      - namenode

  resourcemanager:
    build: ./resourcemanager
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - datanode4
    ports:
      - "8089:8088"
